Repository sohyun23/CRAFTY, pull requests merged in 2023-07, with the labels that each got.

#18 feat: generate registerGoods page
  src/main/java/crafty/controller/HomeController.java
  src/main/resources/static/css/registerGoods.css
  src/main/webapp/WEB-INF/views/registerGoods.jsp
Labels: Mem-front

#20 Develop 1 build login
  src/main/resources/static/css/login.css
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/WEB-INF/views/signUp.jsp
Labels: Mem-front

#22 feat: generate profile Edit page
  src/main/resources/static/css/profileEdit.css
  src/main/webapp/WEB-INF/views/profileEdit.jsp
Labels: Mem-front

#24 feat : generate common.css
  src/main/resources/static/css/common.css
Labels: Mem-front, Admin-Front

#25 feat : generate header.jsp, footer.jsp
  src/main/webapp/WEB-INF/views/footer.jsp
  src/main/webapp/WEB-INF/views/header.jsp
Labels: Mem-front, Admin-Front

#27 fix : common.css
  src/main/resources/static/css/common.css
Labels: Mem-front

#28 feat : generate main-page
  src/main/java/crafty/controller/HomeController.java
  src/main/java/crafty/pagination/dto/MainCard.java
  src/main/java/crafty/pagination/dto/SearchKeyword.java
  src/main/resources/static/css/mainLayout.css
  src/main/webapp/WEB-INF/views/main.jsp
Labels: Mem-front

#29 fix: profileEdit
  src/main/resources/static/css/profileEdit.css
  src/main/webapp/WEB-INF/views/profileEdit.jsp
Labels: Mem-front

#30 fix: registerGoods
  src/main/resources/static/css/registerGoods.css
  src/main/webapp/WEB-INF/views/registerGoods.jsp
Labels: Mem-front

#31 feat:generate goodsDetail Page
  src/main/webapp/WEB-INF/views/goodsDetail.jsp
  src/main/webapp/resources/css/goodsDetail.css
Labels: Mem-front

#33 feat: generate registeredGoodsDetail page
  src/main/resources/static/css/registeredGoodsDetail.css
  src/main/webapp/WEB-INF/views/registeredGoodsDetail.jsp
Labels: Mem-front

#34 feat: generate registeredGoodsSalesByItem page
  src/main/resources/static/css/registeredGoodsSalesByItem.css
  src/main/webapp/WEB-INF/views/registeredGoodsSalesByItem.jsp
Labels: Mem-front

#60 feat: generate liked, alarm page
  src/main/resources/static/css/alarmedGoods.css
  src/main/resources/static/css/likedGoods.css
  src/main/webapp/WEB-INF/views/alarmedGoods.jsp
  src/main/webapp/WEB-INF/views/likedGoods.jsp
Labels: Mem-front

#77 feat: get formdata use axios
  HELP.md
  src/main/java/crafty/controller/GoodsController.java
  src/main/java/crafty/dto/Goods.java
  src/main/java/crafty/dto/GoodsDesciptionImg.java
  src/main/java/crafty/dto/GoodsResponse.java
  src/main/java/crafty/dto/Item.java
  src/main/java/crafty/dto/ItemResponse.java
  src/main/java/crafty/service/GoodsDescriptionImgService.java
  src/main/java/crafty/service/GoodsService.java
  src/main/resources/static/css/registerGoods.css
  src/main/webapp/WEB-INF/views/registerGoods.jsp
Labels: back
